### ISSUE TITLE
Добавить index.xml в индексные файлы nginx

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-ru#11]
На будущее, для фидов в статической версии.

**Comment by h4** [comment]
Немного не понял — кто будет ходить и по какому урл?

**Comment by h4** [comment]
@pepelsbey у тебя уведомления из гитхаба починились?

**Comment by pepelsbey** [comment]
Как для Апача ты бы написал `DirectoryIndex index.html index.xml`, так и для nginx хочется сделать такое же. Уведомления вроде ходят, но никогда не знаешь наверняка.

**Comment by h4** [comment]
А, понял. Чтобы `http://web-standards.ru/feed/` отдавал `http://web-standards.ru/feed/index.xml`.

**Comment by pepelsbey** [comment]
Именно!

**Comment by pepelsbey** [comment]
Закрываю, пока это из области фантастики
