### ISSUE TITLE
Let’s Talk about Semantics

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-ru#13]
[Черновик в админке](http://web-standards.ru/wp-admin/post.php?post=623&action=edit)
- [x] Прочитать, убедиться, что текст готов к публикации
- [x] Сравнить с оригинальным текстом, насколько он обновился
- [x] Проверить подвал с выходными данными
- [x] Добавить лид в поле «Цитата» (скомбинировать вводный абзац)
- [x] Пнуть @pepelsbey, чтобы перевёл картинку и запланировал публикацию

**Comment by tachisis** [comment]
Текст проверен и отредактирован. Нужно перевести картинку-схему и вставить ссылку на нее в двух местах статьи.
