### ISSUE TITLE
Displaying and detecting support for SVG images

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/web-standards-ru#16]
[Черновик в админке](http://web-standards.ru/wp-admin/post.php?post=814&action=edit)

- [ ] Прочитать, убедиться, что текст готов к публикации
- [ ] Сравнить с оригинальным текстом, насколько он обновился
- [x] Спросить в чатике, насколько текст устарел, у @yoksel, например
- [ ] Проверить подвал с выходными данными
- [ ] Добавить лид в поле «Цитата» (скомбинировать вводный абзац)
- [ ] Пнуть @pepelsbey, чтобы запланировал публикацию

**Comment by tachisis** [comment]
@yoksel постановила, что текст устарел. Что с ним сделать?

**Comment by pepelsbey** [comment]
Убить текст из админки, что ещё делать :\

**Comment by tachisis** [comment]
Есть, сэр
