### ISSUE TITLE
«Фирменный стиль»?

### ISSUE THREAD

**Issue by kizu** [web-standards-ru/web-standards-ru#2]
Нам надо решить, что же является элементами фирменного стиля нашей тусовки.

Плюс, надо решить что мы хотим из этого поменять, что можем, а для чего было бы здорово привлечь стороннюю помощь в лице каких-нибудь дизайнеров.

Из того, что *мне лично* хочется сохранить:

1. Основные цвета. Разве что, возможно, имеет смысл их сделать чуть ярче и чище — я бы поставил такую задачу какому-нибудь дизайнеру.

2. Логотип. В минималистичном варианте он выглядит отлично. Три квадратика фирменных цветов — что ещё нужно? Кажется, что оптимальный вариант, в который можно это развить — постоянно как-то это дело обыгрывать, не оставляя какой-то вариант «основным». Т.е. везде по умолчанию используем «плоский» минималистичный вариант, но везде к месту было бы здорово как-то что-то подправлять и намекать в иллюстрациях к статьям и оформлении сайтов на логотип. Это может быть как progressive enhancement в логотипе, как предложил Лев Солнцев, но такой эксперимент хорошо может подойти где-то в статье про этот самый progressive enhancement, тогда как делать подобную вариацию основой — не нужно.

    Возможно, можно также найти каких-нибудь дизайнеров, специализирующихся на фирменном стиле и спросить как можно «осовременить» логотип без потери его простоты и узнаваемости.

И, на самом деле, всё. Если у нас сохранятся цвета и логотип, то все остальные имеющиеся элементы могут быть изменены. Мы же делаем что-то с ноля — не обязательно оставлять старый размер шрифта, как и выбор гарнитур для тела и заголовков. Можно будет попробовать «поиграть» с какими-нибудь из иных шрифтов, а то и посмотреть в сторону того, чтобы приобрести шрифт специально для сайта. Вдруг, найдутся интересные решения, которые могли бы нам подойти?

Если кто-то видит что-то ещё, что можно и нужно оставить «в наследство» — высказывайтесь. Также приветствуются любые идеи по тому, что я уже описал.

**Comment by a-x-** [comment]
:+1: 
И хорошо бы запланировать редизайн сайта http://web-standards.ru, хотя бы потому, что он выглядит старо, что не считается с динамичной отраслью в которой он находится.

**Comment by a-x-** [comment]
Такой дизайн отпугивает от желания взглянуть на контент.

**Comment by h4** [comment]
@a-x- если у вас есть знакомый хороший дизайнер — отправьте, пожалуйста, его контакты по почте wst@web-standards.ru

**Comment by a-x-** [comment]
Увы, нет

12 апреля 2015 г., 19:27 пользователь Mikhail Baranov <
notifications@github.com> написал:

**Comment by pepelsbey** [comment]
По фирстилю началось движение, так что спасибо всем за дискуссию
