### ISSUE TITLE
Не отображаются блоки кода в Pocket

### ISSUE THREAD

**Issue by h4** [web-standards-ru/web-standards-ru#26]
Например, вот эта статья http://web-standards.ru/articles/web-font-loading-patterns/

**Comment by pepelsbey** [comment]
Ну, дурак этот Pocket. Это единственный правильный и самый распространённый способ вставки кода, [см. фид](http://web-standards.ru/feed/):

```
<p>Чтобы не перегружать паттерны…</p>

<pre><code>@font-face {
    font-family: Output Sans;
    src: url(output-sans.woff2) format('woff2'),
         url(output-sans.woff) format('woff');
}</code></pre>
```

Моя RSS-читалка Reeder всё прекрасно показывает.

**Comment by pepelsbey** [comment]
Скрин? Аналогичные сайты?

**Comment by igoradamenko** [comment]
Покет ведёт себя в этом плане относительно странно. У Хабра вроде как код оформлен аналогичным образом. Например: https://habrahabr.ru/post/304608/

```
<pre><code class="javascript hljs"><span class="hljs-keyword">var</span> DataObject = AbstractData.subclass({
    propertyDescriptors: {
      delegate: <span class="hljs-string">'delegateChanged'</span>,
      target: <span class="hljs-string">'targetChanged'</span>,
      root: <span class="hljs-string">'rootChanged'</span>,
      data: {
        nested: <span class="hljs-literal">true</span>,
        events: <span class="hljs-string">'update'</span>
      }
    },

   <span class="hljs-comment">// ...</span>
}
</code></pre>
```

Однако в Покете он виден:
![pocket](https://cloud.githubusercontent.com/assets/6537798/16544472/4fe226f0-4110-11e6-88a9-cb549ae2d897.jpg)

Может быть это связано с тем, что Хабр [зарегистрирован в Покете как поставщик контента](https://getpocket.com/publisher/)? Судя по этому коду в шапке:

`<meta name="pocket-site-verification" content="ed24b2b9721edf0a282c5b4a3232c4" />`

**Comment by igoradamenko** [comment]
Задал этот вопрос поддержке Покета. Когда (и если) ответят — напишу.

**Comment by igoradamenko** [comment]
> Thank you for contacting Pocket Support. I am sorry to hear you are having issues with code blocks being displayed in Pocket.
> 
> It seems the issue you are reporting is related to our parser which is in charge of extracting the content from a page and displaying it optimally in Pocket. I was able to reproduce the issue you are seeing with this particular article. I sent a ticket to our developers so they can look into the issue. If you find any other article issues, please send them my way!

Не знаю, ответят ли они мне, когда это пофиксят, но предлагаю на время с этим смириться и закрыть ишью :koala:

**Comment by pepelsbey** [comment]
@igoradamenko, спасибо за расследование!
