### ISSUE TITLE
Возобновить проект

### ISSUE THREAD

**Issue by alexbaumgertner** [web-standards-ru/web-standards-ru#27]
Сегодня на https://wsd.events/2018/08/18/ обсудили, что было бы круто воскресить и обновить сайт.
- [x] Новый дизайн
- [x] Новый бекенд
- [x] Новый фронтенд

Я готов помочь по фронтенду. Если бекенд будет на nodejs — то и по бекенду.
/cc @nikolay-govorov

**Comment by alexbaumgertner** [comment]
Нужно только Виденье проекта от Вадима @pepelsbey

**Comment by Ermakoy** [comment]
Отличная идея! Готов посильно помочь с фронтендом и организацией.

**Comment by pepelsbey** [comment]
@alexbaumgertner @Ermakoy, встретились сегодня инициативной группой и обсудили, что будет дальше, см. [web-standards-ru/projects/1](https://github.com/orgs/web-standards-ru/projects/1), проект будем вести в [web-standards-ru/new](https://github.com/web-standards-ru/new)

**Comment by alexbaumgertner** [comment]
https://github.com/orgs/web-standards-ru/projects/1 — 404 not found

Нашел общую задачу в https://github.com/web-standards-ru/new/issues/1

**Comment by pepelsbey** [comment]
@alexbaumgertner сделал проект публичным

**Comment by alexbaumgertner** [comment]
Спасибо, теперь открывается!
